# Generated by Django 5.1.6 on 2025-02-11 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('other_names', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('A', 'A'), ('C', 'C'), ('B', 'B')], max_length=1)),
                ('language', models.CharField(choices=[('E', 'E'), ('F', 'F'), ('S', 'S')], max_length=1)),
            ],
        ),
    ]
