# Generated by Django 5.1.6 on 2025-02-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_last_login_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
    ]
