# Generated by Django 5.1.6 on 2025-04-14 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appointments', '0003_appointment_pricing'),
        ('Services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provider_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Appointments.appointment')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Services.pricing')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderPaystackAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_subaccount_id', models.CharField(max_length=100, unique=True)),
                ('paystack_secret_key', models.CharField(max_length=100)),
                ('paystack_public_key', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('settlement_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_money_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Provider Paystack Account',
                'verbose_name_plural': 'Service Provider Paystack Accounts',
            },
        ),
    ]
