# Generated by Django 5.1.6 on 2025-04-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_appointment_service'),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.pricing'),
        ),
    ]
