# Generated by Django 5.1.6 on 2025-04-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_appointment_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('X', 'Canceled'), ('PP', 'Payment Pending'), ('PF', 'Payment Failed')], default='PP', max_length=2),
        ),
    ]
