# Generated by Django 4.2.16 on 2025-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_alter_usernotificationpreference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='html_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='mailersend_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
